version: '3.8'
services:
  backend:
    build: ./backend
    container_name: obligat-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - obligat-net
  frontend:
    build: ./frontend
    container_name: obligat-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - obligat-net
networks:
  obligat-net:
    driver: bridge 